# Generated by Django 2.2.5 on 2019-10-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCard_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('tag', models.CharField(choices=[('eng', 'eng'), ('ar', 'ar')], default='eng', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='paymax_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('tag', models.CharField(choices=[('eng', 'eng'), ('ar', 'ar')], default='eng', max_length=5)),
            ],
        ),
    ]
