# Generated by Django 2.2.5 on 2020-05-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charges_headline',
            name='tag',
            field=models.CharField(choices=[('eng', 'eng'), ('ar', 'ar')], default='eng', max_length=5),
        ),
    ]
