# Generated by Django 2.2.5 on 2019-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tag',
            field=models.CharField(choices=[('eng', 'eng'), ('ar', 'ar')], default='eng', max_length=5),
        ),
        migrations.AddField(
            model_name='partners_main',
            name='tag',
            field=models.CharField(choices=[('eng', 'eng'), ('ar', 'ar')], default='eng', max_length=5),
        ),
    ]
