# Generated by Django 2.2.5 on 2019-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20191017_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='points',
            field=models.ManyToManyField(blank=True, to='partners.points'),
        ),
    ]
