# Generated by Django 2.2.5 on 2019-10-17 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20191017_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
