# Generated by Django 2.2.5 on 2019-10-17 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_detail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
