# Generated by Django 2.2.5 on 2019-10-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology_detail',
            name='sub_title',
        ),
    ]
