# Generated by Django 2.2.5 on 2019-10-17 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technology', '0002_remove_technology_detail_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology_detail',
            name='main_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='technology_detail',
            name='sub_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
