# Generated by Django 2.2.5 on 2020-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download_centre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download_details',
            name='name',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
