# Generated by Django 2.2.5 on 2019-10-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_paymentcard_detail_paymentcard_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider_detail',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.slider_image'),
        ),
    ]
