# Generated by Django 2.2.5 on 2019-10-17 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191017_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_detail',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
