# Generated by Django 2.2.5 on 2020-05-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191017_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_detail',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
