# Generated by Django 2.2.5 on 2019-10-17 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191014_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
